add_library(DataTest STATIC MakeMeshData.cpp)
target_link_libraries(DataTest PUBLIC Data)
target_include_directories(DataTest PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

precess_add_test(TestModelManager TestModelManager.cpp)
precess_test_link_libraries(TestModelManager DataTest Data)

precess_add_test(TestComponentModel TestComponentModel.cpp)
precess_test_link_libraries(TestComponentModel Data)

precess_add_test(TestGeometryIndex TestGeometryIndex.cpp)
precess_test_link_libraries(TestGeometryIndex Data TKPrim TKBRep TKTopAlgo)

precess_add_test(TestElementIDMap TestElementIDMap.cpp)
precess_test_link_libraries(TestElementIDMap Data)

precess_add_test(TestComponentOperator TestComponentOperator.cpp)
precess_test_link_libraries(TestComponentOperator Data)

precess_add_test(TestGlobalPoints TestGlobalPoints.cpp)
precess_test_link_libraries(TestGlobalPoints Data)

precess_add_test(TestGeometryMeshMap TestGeometryMeshMap.cpp)
precess_test_link_libraries(TestGeometryMeshMap Data)

precess_add_test(TestMeshAdjacency TestMeshAdjacency.cpp)
precess_test_link_libraries(TestMeshAdjacency Data)