name: 功能建议
description: 对本项目提出一个功能建议
title: "[功能建议]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢提出功能建议，我们将仔细考虑！
  - type: textarea
    id: related-problem
    attributes:
      label: 这个功能建议和一个你遇到的问题/困扰相关吗？或者说该功能有什么实用价值吗？请你描述一下。
      description: 清晰并简洁地描述问题是什么，例如，我想做……的时候总是很不方便，……
    validations:
      required: false
  - type: textarea
    id: desired-solution
    attributes:
      label: 描述你想要添加的功能实现，你希望看到这个问题该如何解决？
      description: 清晰并简洁地描述你的设想，这个功能实现了应该是什么样的。
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 描述你考虑过的其他实现方案。
      description: 如果有的话，清晰并简洁地描述你考虑过的其他解决方案或功能实现。
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 还有其他有用的信息或截图吗？
      description: 在这填写关于功能建议的其他信息或截图。
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 意向参与贡献
      options:
        - label: 我有意向参与具体功能的开发实现并将代码贡献回到上游社区
          required: false