blank_issues_enabled: false
contact_links:
  - name: 群聊支持 Group Support
    url: https://gitee.com/precess/PreCess#%E8%81%94%E7%B3%BB%E6%96%B9%E5%BC%8F
    about: 通过群聊寻求支持。 Ask questions and find answers from the group.