add_subdirectory(FeatureDemoPlugin)
add_subdirectory(MeshQualityPlugin)
add_subdirectory(MeshRepairPlugin)
add_subdirectory(MeshBooleanPlugin)
add_subdirectory(MeasurePlugin)
add_subdirectory(DimensionPlugin)
add_subdirectory(ScalePreviewPlugin)
add_subdirectory(CreateBoxPlugin)
add_subdirectory(CreateConePlugin)
add_subdirectory(CreateCylinderPlugin)
add_subdirectory(CreateDiskFacePlugin)
add_subdirectory(CreateFaceFromEdgesPlugin)
add_subdirectory(CreateLineByCoordinatesPlugin)
add_subdirectory(CreateLineFromVerticesPlugin)
add_subdirectory(CreatePointPlugin)
add_subdirectory(CreateRectangleFacePlugin)
add_subdirectory(CreateSpherePlugin)
add_subdirectory(DeleteGeometryPlugin)
add_subdirectory(ExtrudeFacePlugin)
