name: Doxygen Action
run-name: Generating Doxygen Page...

on:
  push:
    branches: [ develop ]

jobs:
  gen-doxygen-page:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.8

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
